# Generated by Django 5.1.3 on 2025-03-02 12:36

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='TargetsData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('instagram_id', models.CharField(blank=True, max_length=10000, null=True)),
                ('username', models.CharField(blank=True, max_length=10000, null=True)),
                ('full_name', models.CharField(blank=True, max_length=10000, null=True)),
                ('follower_count', models.CharField(blank=True, max_length=10000, null=True)),
                ('following_count', models.CharField(blank=True, max_length=10000, null=True)),
                ('media_count', models.CharField(blank=True, max_length=10000, null=True)),
                ('biography', models.CharField(blank=True, max_length=10000, null=True)),
                ('is_verified', models.CharField(blank=True, max_length=10000, null=True)),
                ('is_whatsapp_linked', models.CharField(blank=True, max_length=10000, null=True)),
                ('bio_links', models.CharField(blank=True, max_length=10000, null=True)),
                ('has_highlight_reels', models.CharField(blank=True, max_length=10000, null=True)),
                ('has_music_on_profile', models.CharField(blank=True, max_length=10000, null=True)),
                ('is_private', models.CharField(blank=True, max_length=10000, null=True)),
                ('can_hide_category', models.CharField(blank=True, max_length=10000, null=True)),
                ('show_fb_link_on_profile', models.CharField(blank=True, max_length=10000, null=True)),
                ('show_fb_page_link_on_profile', models.CharField(blank=True, max_length=10000, null=True)),
                ('ads_page_id', models.CharField(blank=True, max_length=10000, null=True)),
                ('ads_page_name', models.CharField(blank=True, max_length=10000, null=True)),
                ('account_category', models.CharField(blank=True, max_length=10000, null=True)),
                ('is_business', models.CharField(blank=True, max_length=10000, null=True)),
                ('category', models.CharField(blank=True, max_length=10000, null=True)),
                ('is_new_to_instagram', models.CharField(blank=True, max_length=10000, null=True)),
                ('is_parenting_account', models.CharField(blank=True, max_length=10000, null=True)),
                ('page_id', models.CharField(blank=True, max_length=10000, null=True)),
                ('page_name', models.CharField(blank=True, max_length=10000, null=True)),
                ('birthday_today_visibility_for_viewer', models.CharField(blank=True, max_length=10000, null=True)),
                ('fan_club_info', models.CharField(blank=True, max_length=10000, null=True)),
                ('hd_profile_pic_url', models.CharField(blank=True, max_length=10000, null=True)),
            ],
        ),
    ]
