# Generated by Django 5.1.3 on 2025-03-02 13:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('targets_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='targetsdata',
            name='profile_image',
            field=models.FileField(blank=True, null=True, upload_to='%Y/%m/%d'),
        ),
    ]
