# Generated by Django 5.1.3 on 2025-03-06 09:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('targets_app', '0002_targetsdata_profile_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='targetsdata',
            name='account_category',
        ),
        migrations.RemoveField(
            model_name='targetsdata',
            name='ads_page_id',
        ),
        migrations.RemoveField(
            model_name='targetsdata',
            name='ads_page_name',
        ),
        migrations.RemoveField(
            model_name='targetsdata',
            name='birthday_today_visibility_for_viewer',
        ),
        migrations.RemoveField(
            model_name='targetsdata',
            name='can_hide_category',
        ),
        migrations.RemoveField(
            model_name='targetsdata',
            name='fan_club_info',
        ),
        migrations.RemoveField(
            model_name='targetsdata',
            name='has_highlight_reels',
        ),
        migrations.RemoveField(
            model_name='targetsdata',
            name='has_music_on_profile',
        ),
        migrations.RemoveField(
            model_name='targetsdata',
            name='is_new_to_instagram',
        ),
        migrations.RemoveField(
            model_name='targetsdata',
            name='is_parenting_account',
        ),
        migrations.RemoveField(
            model_name='targetsdata',
            name='is_private',
        ),
        migrations.RemoveField(
            model_name='targetsdata',
            name='is_whatsapp_linked',
        ),
        migrations.RemoveField(
            model_name='targetsdata',
            name='page_id',
        ),
        migrations.RemoveField(
            model_name='targetsdata',
            name='page_name',
        ),
        migrations.RemoveField(
            model_name='targetsdata',
            name='show_fb_link_on_profile',
        ),
        migrations.RemoveField(
            model_name='targetsdata',
            name='show_fb_page_link_on_profile',
        ),
        migrations.AddField(
            model_name='targetsdata',
            name='biography_with_entities',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='targetsdata',
            name='bio_links',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='targetsdata',
            name='biography',
            field=models.TextField(blank=True, null=True),
        ),
    ]
