# Generated by Django 5.1.3 on 2025-03-06 10:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('targets_app', '0003_remove_targetsdata_account_category_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='targetsdata',
            name='bio_links',
        ),
        migrations.AlterField(
            model_name='targetsdata',
            name='profile_image',
            field=models.FileField(blank=True, null=True, upload_to='files/%Y/%m/%d'),
        ),
        migrations.CreateModel(
            name='TargetBioLinks',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bio_title', models.CharField(blank=True, max_length=10000, null=True)),
                ('bio_url', models.CharField(blank=True, max_length=10000, null=True)),
                ('target_db_data', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='targets_app.targetsdata')),
            ],
        ),
    ]
