# Generated by Django 5.1.3 on 2025-03-06 10:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('targets_app', '0004_remove_targetsdata_bio_links_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='TargetAccountHashtags',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hashtag_name', models.CharField(blank=True, max_length=10000, null=True)),
                ('hashtag_id', models.CharField(blank=True, max_length=10000, null=True)),
                ('target_db_data', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='targets_app.targetsdata')),
            ],
        ),
    ]
