# Generated by Django 5.1.3 on 2025-03-07 09:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('targets_app', '0005_targetaccounthashtags'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='targetsdata',
            name='biography_with_entities',
        ),
    ]
