# Generated by Django 5.1.3 on 2025-03-08 07:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('targets_app', '0006_remove_targetsdata_biography_with_entities'),
    ]

    operations = [
        migrations.AddField(
            model_name='targetsdata',
            name='is_private',
            field=models.CharField(blank=True, max_length=10000, null=True),
        ),
    ]
