# Generated by Django 5.1.3 on 2025-03-08 12:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('targets_app', '0008_targetfollowersdata'),
    ]

    operations = [
        migrations.AddField(
            model_name='targetfollowersdata',
            name='profile_image',
            field=models.FileField(blank=True, null=True, upload_to='files/%Y/%m/%d'),
        ),
        migrations.AlterField(
            model_name='targetfollowersdata',
            name='profile_pic_url',
            field=models.TextField(blank=True, null=True),
        ),
    ]
