# Generated by Django 5.1.3 on 2025-03-15 08:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('targets_app', '0009_targetfollowersdata_profile_image_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='targetsdata',
            name='fan_club_info',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='targetsdata',
            name='has_highlight_reels',
            field=models.CharField(blank=True, max_length=10000, null=True),
        ),
        migrations.AddField(
            model_name='targetsdata',
            name='has_music_on_profile',
            field=models.CharField(blank=True, max_length=10000, null=True),
        ),
        migrations.AddField(
            model_name='targetsdata',
            name='is_new_to_instagram',
            field=models.CharField(blank=True, max_length=10000, null=True),
        ),
        migrations.AddField(
            model_name='targetsdata',
            name='is_profile_picture_expansion_enabled',
            field=models.CharField(blank=True, max_length=10000, null=True),
        ),
        migrations.AddField(
            model_name='targetsdata',
            name='profile_pic_id',
            field=models.CharField(blank=True, max_length=10000, null=True),
        ),
        migrations.AlterField(
            model_name='targetsdata',
            name='hd_profile_pic_url',
            field=models.TextField(blank=True, null=True),
        ),
    ]
