# Generated by Django 5.1.3 on 2025-03-15 09:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('targets_app', '0010_targetsdata_fan_club_info_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='targetfollowersdata',
            name='profile_pic_id',
        ),
    ]
