# Generated by Django 5.1.3 on 2025-03-16 09:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('targets_app', '0011_remove_targetfollowersdata_profile_pic_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='TargetFollowingsData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('instagram_id', models.CharField(blank=True, max_length=10000, null=True)),
                ('username', models.CharField(blank=True, max_length=10000, null=True)),
                ('full_name', models.CharField(blank=True, max_length=10000, null=True)),
                ('is_private', models.CharField(blank=True, max_length=10000, null=True)),
                ('is_verified', models.CharField(blank=True, max_length=10000, null=True)),
                ('profile_pic_url', models.TextField(blank=True, null=True)),
                ('profile_image', models.FileField(blank=True, null=True, upload_to='files/%Y/%m/%d')),
                ('target_db_data', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='targets_app.targetsdata')),
            ],
        ),
    ]
