# Generated by Django 5.1.3 on 2025-03-18 09:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('targets_app', '0012_targetfollowingsdata'),
    ]

    operations = [
        migrations.CreateModel(
            name='TargetPostsData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('taken_at', models.CharField(blank=True, max_length=10000, null=True)),
                ('post_pk', models.CharField(blank=True, max_length=10000, null=True)),
                ('post_id', models.CharField(blank=True, max_length=10000, null=True)),
                ('caption_is_edited', models.CharField(blank=True, max_length=10000, null=True)),
                ('share_count_disabled', models.CharField(blank=True, max_length=10000, null=True)),
                ('like_and_view_counts_disabled', models.CharField(blank=True, max_length=10000, null=True)),
                ('is_quiet_post', models.CharField(blank=True, max_length=10000, null=True)),
                ('has_privately_liked', models.CharField(blank=True, max_length=10000, null=True)),
                ('code', models.CharField(blank=True, max_length=10000, null=True)),
                ('caption', models.TextField(blank=True, null=True)),
                ('can_reply', models.CharField(blank=True, max_length=10000, null=True)),
                ('comment_count', models.CharField(blank=True, max_length=10000, null=True)),
                ('like_count', models.CharField(blank=True, max_length=10000, null=True)),
                ('top_likers', models.TextField(blank=True, null=True)),
                ('can_viewer_save', models.CharField(blank=True, max_length=10000, null=True)),
                ('can_viewer_reshare', models.CharField(blank=True, max_length=10000, null=True)),
                ('cover_image', models.FileField(blank=True, null=True, upload_to='')),
                ('target_db_data', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='targets_app.targetsdata')),
            ],
        ),
        migrations.CreateModel(
            name='PostsContentsData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content_file', models.FileField(blank=True, null=True, upload_to='')),
                ('post_db_data', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='targets_app.targetpostsdata')),
            ],
        ),
    ]
