# Generated by Django 5.1.3 on 2025-03-18 09:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('targets_app', '0013_targetpostsdata_postscontentsdata'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='PostsContentsData',
            new_name='TargetPostsContentsData',
        ),
    ]
