# Generated by Django 5.1.3 on 2025-03-19 08:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('targets_app', '0014_rename_postscontentsdata_targetpostscontentsdata'),
    ]

    operations = [
        migrations.AlterField(
            model_name='targetfollowersdata',
            name='profile_image',
            field=models.FileField(blank=True, null=True, upload_to='files/profile_images'),
        ),
        migrations.AlterField(
            model_name='targetfollowingsdata',
            name='profile_image',
            field=models.FileField(blank=True, null=True, upload_to='files/profile_images'),
        ),
        migrations.AlterField(
            model_name='targetpostscontentsdata',
            name='content_file',
            field=models.FileField(blank=True, null=True, upload_to='files/posts_contents'),
        ),
        migrations.AlterField(
            model_name='targetpostsdata',
            name='cover_image',
            field=models.FileField(blank=True, null=True, upload_to='files/posts_cover_images'),
        ),
        migrations.AlterField(
            model_name='targetsdata',
            name='profile_image',
            field=models.FileField(blank=True, null=True, upload_to='files/profile_images'),
        ),
    ]
