# Generated by Django 5.1.3 on 2025-03-19 08:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('targets_app', '0015_alter_targetfollowersdata_profile_image_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='targetpostsdata',
            name='top_likers',
        ),
    ]
