# Generated by Django 5.1.3 on 2025-03-21 08:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('targets_app', '0016_remove_targetpostsdata_top_likers'),
    ]

    operations = [
        migrations.AlterField(
            model_name='targetbiolinks',
            name='bio_url',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.CreateModel(
            name='TargetPostLikesData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('instagram_pk', models.CharField(blank=True, max_length=10000, null=True)),
                ('instagram_id', models.CharField(blank=True, max_length=10000, null=True)),
                ('username', models.CharField(blank=True, max_length=10000, null=True)),
                ('full_name', models.CharField(blank=True, max_length=10000, null=True)),
                ('is_private', models.CharField(blank=True, max_length=10000, null=True)),
                ('is_verified', models.CharField(blank=True, max_length=10000, null=True)),
                ('profile_pic_url', models.TextField(blank=True, null=True)),
                ('is_new', models.CharField(blank=True, max_length=10000, null=True)),
                ('profile_image', models.FileField(blank=True, null=True, upload_to='files/profile_images')),
                ('post_db_data', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='targets_app.targetpostsdata')),
            ],
        ),
    ]
