# Generated by Django 5.1.3 on 2025-03-22 09:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('targets_app', '0017_alter_targetbiolinks_bio_url_targetpostlikesdata'),
    ]

    operations = [
        migrations.CreateModel(
            name='TargetPostCommentsData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('instagram_pk', models.CharField(blank=True, max_length=10000, null=True)),
                ('instagram_id', models.CharField(blank=True, max_length=10000, null=True)),
                ('username', models.CharField(blank=True, max_length=10000, null=True)),
                ('full_name', models.CharField(blank=True, max_length=10000, null=True)),
                ('is_private', models.CharField(blank=True, max_length=10000, null=True)),
                ('is_verified', models.CharField(blank=True, max_length=10000, null=True)),
                ('did_report_as_spam', models.CharField(blank=True, max_length=10000, null=True)),
                ('created_at', models.CharField(blank=True, max_length=10000, null=True)),
                ('share_enabled', models.CharField(blank=True, max_length=10000, null=True)),
                ('text', models.TextField(blank=True, null=True)),
                ('comment_like_count', models.CharField(blank=True, max_length=10000, null=True)),
                ('profile_pic_url', models.TextField(blank=True, null=True)),
                ('profile_image', models.FileField(blank=True, null=True, upload_to='files/profile_images')),
                ('post_db_data', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='targets_app.targetpostsdata')),
            ],
        ),
    ]
