# Generated by Django 5.1.3 on 2025-03-22 10:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('targets_app', '0019_targetstoriesdata'),
    ]

    operations = [
        migrations.CreateModel(
            name='TargetHighlightsData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('instagram_id', models.CharField(blank=True, max_length=10000, null=True)),
                ('title', models.CharField(blank=True, max_length=10000, null=True)),
                ('cover_image', models.FileField(blank=True, null=True, upload_to='files/highlights_cover_images')),
                ('target_db_data', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='targets_app.targetsdata')),
            ],
        ),
    ]
