# Generated by Django 5.1.3 on 2025-03-22 10:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('targets_app', '0020_targethighlightsdata'),
    ]

    operations = [
        migrations.CreateModel(
            name='TargetHighlightDetailsData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('instagram_pk', models.CharField(blank=True, max_length=10000, null=True)),
                ('instagram_id', models.CharField(blank=True, max_length=10000, null=True)),
                ('taken_at', models.CharField(blank=True, max_length=10000, null=True)),
                ('like_and_view_counts_disabled', models.CharField(blank=True, max_length=10000, null=True)),
                ('is_reel_media', models.CharField(blank=True, max_length=10000, null=True)),
                ('commenting_disabled_for_viewer', models.CharField(blank=True, max_length=10000, null=True)),
                ('can_viewer_save', models.CharField(blank=True, max_length=10000, null=True)),
                ('code', models.CharField(blank=True, max_length=10000, null=True)),
                ('can_reply', models.CharField(blank=True, max_length=10000, null=True)),
                ('can_reshare', models.CharField(blank=True, max_length=10000, null=True)),
                ('caption', models.TextField(blank=True, null=True)),
                ('cover_image', models.FileField(blank=True, null=True, upload_to='files/stories_cover_images')),
                ('video_file', models.FileField(blank=True, null=True, upload_to='files/stories_contents')),
                ('highlight_db_data', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='targets_app.targethighlightsdata')),
            ],
        ),
    ]
