# Generated by Django 5.1.3 on 2025-03-24 08:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('targets_app', '0021_targethighlightdetailsdata'),
    ]

    operations = [
        migrations.AlterField(
            model_name='targetpostsdata',
            name='taken_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
