# Generated by Django 5.1.3 on 2025-03-24 09:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('targets_app', '0022_alter_targetpostsdata_taken_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='targethighlightdetailsdata',
            name='taken_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='targetpostcommentsdata',
            name='created_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='targetstoriesdata',
            name='expiring_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='targetstoriesdata',
            name='taken_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
