# Generated by Django 5.1.3 on 2025-04-23 14:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('targets_app', '0023_alter_targethighlightdetailsdata_taken_at_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='targetfollowersdata',
            name='profile_image',
            field=models.FileField(blank=True, null=True, upload_to='profile_images'),
        ),
        migrations.AlterField(
            model_name='targetfollowingsdata',
            name='profile_image',
            field=models.FileField(blank=True, null=True, upload_to='profile_images'),
        ),
        migrations.AlterField(
            model_name='targethighlightdetailsdata',
            name='cover_image',
            field=models.FileField(blank=True, null=True, upload_to='stories_cover_images'),
        ),
        migrations.AlterField(
            model_name='targethighlightdetailsdata',
            name='video_file',
            field=models.FileField(blank=True, null=True, upload_to='stories_contents'),
        ),
        migrations.AlterField(
            model_name='targethighlightsdata',
            name='cover_image',
            field=models.FileField(blank=True, null=True, upload_to='highlights_cover_images'),
        ),
        migrations.AlterField(
            model_name='targetpostcommentsdata',
            name='profile_image',
            field=models.FileField(blank=True, null=True, upload_to='profile_images'),
        ),
        migrations.AlterField(
            model_name='targetpostlikesdata',
            name='profile_image',
            field=models.FileField(blank=True, null=True, upload_to='profile_images'),
        ),
        migrations.AlterField(
            model_name='targetpostscontentsdata',
            name='content_file',
            field=models.FileField(blank=True, null=True, upload_to='posts_contents'),
        ),
        migrations.AlterField(
            model_name='targetpostsdata',
            name='cover_image',
            field=models.FileField(blank=True, null=True, upload_to='posts_cover_images'),
        ),
        migrations.AlterField(
            model_name='targetsdata',
            name='profile_image',
            field=models.FileField(blank=True, null=True, upload_to='profile_images'),
        ),
        migrations.AlterField(
            model_name='targetstoriesdata',
            name='cover_image',
            field=models.FileField(blank=True, null=True, upload_to='stories_cover_images'),
        ),
        migrations.AlterField(
            model_name='targetstoriesdata',
            name='video_file',
            field=models.FileField(blank=True, null=True, upload_to='stories_contents'),
        ),
    ]
