# Generated by Django 5.1.3 on 2025-02-27 09:46

import django.db.models.manager
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='UsersData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('user_full_name', models.CharField(blank=True, max_length=200, null=True)),
                ('user_code', models.CharField(blank=True, max_length=200, null=True, unique=True)),
                ('user_last_login', models.CharField(blank=True, max_length=200, null=True)),
                ('is_staff', models.BooleanField(blank=True, default=False, null=True)),
            ],
            options={
                'abstract': False,
            },
            managers=[
                ('object', django.db.models.manager.Manager()),
            ],
        ),
    ]
