# Generated by Django 5.1.3 on 2025-05-04 09:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auth_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='usersdata',
            name='user_admin_permission',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
