# Generated by Django 5.1.3 on 2025-05-04 09:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auth_app', '0002_usersdata_user_admin_permission'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='usersdata',
            managers=[
            ],
        ),
        migrations.AlterField(
            model_name='usersdata',
            name='user_last_login',
            field=models.DateTimeField(blank=True, max_length=200, null=True),
        ),
    ]
