# Generated by Django 5.1.3 on 2025-04-23 15:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('scraper_app', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ScrapedFollowersList',
        ),
    ]
